# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcfTigd9UcCqXqXqU-ZFkTn-uQZ1Ew7r
"""

import json
from google.colab import files
uploaded = files.upload()



f = open('source_file_2.json',) 
  
# returns JSON object as  
# a dictionary 
data = json.load(f)

from collections import defaultdict 
  
# initializing dict with lists 
# new_dict = defaultdict(list) 
d = {'key': 'value'}
d2 = {'key': 'value'}

key=[]

for x in range(len(data)):
  for y in range(len(data[x]['managers'])):
  
    if(data[x]['managers'][y] not in key and isinstance(data[x]['managers'][y], str) ) :
      key.append(data[x]['managers'][y])
      print(data[x]['managers'][y])   
 
  
  # new_dict[x].append(data[x]['name'])
  # new_dict[x].append(data[x]['priority'])

for manager in key:
  proj =[]
  for x in range(len(data)):
    if( manager in data[x]['managers']):
      proj.append(data[x]['name'])
  d2[manager]=proj

d3 = {'key': 'value'}
for watcher in key:
  proj =[]
  for x in range(len(data)):
    if( watcher in data[x]['watchers']):
      proj.append(data[x]['priority'])
  d3[watcher]=proj

import operator
projects = {'key': 'value'}
for x in range(len(data)):
  projects[data[x]['priority']]=data[x]['name']

# del d3['luanda']
# from collections import OrderedDict
# dd = OrderedDict(sorted(projects.items(), key=lambda x: x[1]))
for x in d3:
  li=[]
  for y in range(len(d3[x])):
    mini=min(d3[x])
    if(mini in projects):
      
      li.append(projects[mini])
  
      d3[x].remove(min(d3[x]))
  d3[x]=li.copy()
# d3

d5 = {'key': 'value'}
for man in key:
  proj =[]
  for x in range(len(data)):
    if( man in data[x]['managers']):
      proj.append(data[x]['priority'])
  d5[man]=proj

for x in d5:
  li=[]
  for y in range(len(d5[x])):
    mini=min(d5[x])
    if(mini in projects):
      
      li.append(projects[mini])
  
      d5[x].remove(min(d5[x]))
  d5[x]=li.copy()



with open('managers.json', 'w') as fp:
    json.dump(d5, fp)

with open('watchers.json', 'w') as fp:
    json.dump(d3, fp)

files.download('watchers.json')

"""# New Section"""